// Code generated by goctl. DO NOT EDIT.
package types

type Codereq struct {
	Email string `json:"email"`
}

type Coderesp struct {
	Status int    `json:"status"`
	Code   string `json:"code"`
}

type Registerreq struct {
	Email string `json:"email"`
	Name  string `json:"name"`
	Pass  string `json:"pass"`
	Code  string `json:"code"`
	Check string `json:"check"`
}

type Registerresp struct {
	Status      int    `json:"status"`
	Accesstoken string `json:"accessToken"`
	Expires     string `json:"expires"`
	Name        string `json:"name"`
}

type Loginreq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Loginresp struct {
	Status      int    `json:"int"`
	Name        string `json:"name"`
	AccessToken string `json:"accessToken"`
	Expires     string `json:"expires"`
}

type Updatepwdreq struct {
	Code     string `json:"code"`
	Check    string `json:"check"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Updatepwdresp struct {
	Status int `json:"status"`
}

type RefreshTokenreq struct {
	Email string `json:"email"`
}

type RefreshTokenresp struct {
	Status  int    `json:"status"`
	Name    string `json:"name"`
	Token   string `json:"token"`
	Expires string `json:"expires"`
}

type Pubkeyresp struct {
	Status int    `json:"status"`
	Pubkey string `json:"pubkey"`
}

type Baseinfor struct {
	Status int  `json:"status"`
	Info   Info `json:"info"`
}

type Info struct {
	AvatarLink string `json:"avatarLink"`
	UserName   string `json:"username"`
	Profession string `json:"profession"`
	Usermail   string `json:"usermail"`
	Type       string `json:"type"`
}

type Settingbasereq struct {
	Name       string `json:"name"`
	Profession string `json:"profession"`
	Type       string `json:"type"`
}

type Settingbaseresp struct {
	Status int `json:"status"`
}

type Settingavareq struct {
}

type Settingavaresp struct {
	Status int `json:"status"`
}

type Articlereq struct {
	Arid      string `json:"arid"`
	Content   string `json:"content"`
	IsPublish bool   `json:"ispublish"`
}

type Articleresp struct {
	Status    int    `json:"status"`
	Arid      string `json:"arid"`
	IsPublish bool   `json:"ispublish"`
}

type Searchreq struct {
	Articlename string `json:"articlename"`
}

type Searchresp struct {
	Status      int       `json:"status"`
	Articlelist []Article `json:"articallist"`
}

type Article struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	Url         string `json:"url"`
	Description string `json:"description"`
	Likes       int    `json:"likes"`
	Reads       int    `json:"reads"`
	Pubtime     string `json:"pubtime"`
	Imglink     string `json:"imglink"`
}

type Getarticlereq struct {
}

type Getarticleresp struct {
	Status      int          `json:"status"`
	Articlelist []GetArticle `json:"articallist"`
}

type GetArticle struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	Url         string `json:"url"`
	Description string `json:"description"`
	Likes       int    `json:"likes"`
	Reads       int    `json:"reads"`
	Pubtime     string `json:"pubtime"`
	Imglink     string `json:"imglink"`
}

type Readarticlereq struct {
	Arid   string `form:"id"`
	Userid string `form:"user,optional"`
}

type Readarticleresp struct {
	Status  int    `json:"status"`
	Content string `json:"content"`
	Title   string `json:"title"`
	IsEdit  bool   `json:"isEdit"`
}
