// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "yourbackend/internal/handler/login"
	refreshToken "yourbackend/internal/handler/refreshToken"
	register "yourbackend/internal/handler/register"
	updatepwd "yourbackend/internal/handler/updatepwd"
	verification_code "yourbackend/internal/handler/verification_code"
	"yourbackend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/code",
				Handler: verification_code.VericodeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/register",
				Handler: register.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/updatepwd",
				Handler: updatepwd.UpdatepwdHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/refreshToken",
				Handler: refreshToken.RefreshTokenHandler(serverCtx),
			},
		},
	)
}
