// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	articlesFieldNames          = builder.RawFieldNames(&Articles{})
	articlesRows                = strings.Join(articlesFieldNames, ",")
	articlesRowsExpectAutoSet   = strings.Join(stringx.Remove(articlesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	articlesRowsWithPlaceHolder = strings.Join(stringx.Remove(articlesFieldNames, "`mongoid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	articlesModel interface {
		Insert(ctx context.Context, data *Articles) (sql.Result, error)
		FindOne(ctx context.Context, mongoid string) (*Articles, error)
		Update(ctx context.Context, data *Articles) error
		Delete(ctx context.Context, mongoid string) error
	}

	defaultArticlesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Articles struct {
		Mongoid    string `db:"mongoid"`
		Title      string `db:"title"`
		Fewcontent string `db:"fewcontent"`
		Likes      int64  `db:"likes"`
		Views      int64  `db:"views"`
		Url        string `db:"url"`
		Pubtime    string `db:"pubtime"`
		Coverlinks string `db:"coverlinks"`
	}
)

func newArticlesModel(conn sqlx.SqlConn) *defaultArticlesModel {
	return &defaultArticlesModel{
		conn:  conn,
		table: "`articles`",
	}
}

func (m *defaultArticlesModel) Delete(ctx context.Context, mongoid string) error {
	query := fmt.Sprintf("delete from %s where `mongoid` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, mongoid)
	return err
}

func (m *defaultArticlesModel) FindOne(ctx context.Context, mongoid string) (*Articles, error) {
	query := fmt.Sprintf("select %s from %s where `mongoid` = ? limit 1", articlesRows, m.table)
	var resp Articles
	err := m.conn.QueryRowCtx(ctx, &resp, query, mongoid)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticlesModel) Insert(ctx context.Context, data *Articles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, articlesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Mongoid, data.Title, data.Fewcontent, data.Likes, data.Views, data.Url, data.Pubtime, data.Coverlinks)
	return ret, err
}

func (m *defaultArticlesModel) Update(ctx context.Context, data *Articles) error {
	query := fmt.Sprintf("update %s set %s where `mongoid` = ?", m.table, articlesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Fewcontent, data.Likes, data.Views, data.Url, data.Pubtime, data.Coverlinks, data.Mongoid)
	return err
}

func (m *defaultArticlesModel) tableName() string {
	return m.table
}
